---
# PersistentVolume for Jenkins 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/docker" 
#hostPath can be defined as per your requirement. Technically you should not use the hostPath :D
---
# PersistentVolume for Jenkins
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvjenkins-claim
  namespace: jenkins
     # PV are not scoped to any namespace, but pvc is associated with the namespace
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi